### ISSUE TITLE
Documentation leads to dead-end

### ISSUE THREAD

**Issue by MRedies** [dftbplus/scalapackfx#1]
If you click on the documentation in the readme.md:

https://aradi.bitbucket.org/scalapackfx/api/annotated.html

you are forwarded to
 
https://bitbucket.org/

Where can I find the correct documentation for this library?

**Comment by aradi** [comment]
You are right, I did not migrate the pages to github (or somewhere else) yet. You can generate the documentation yourself, though, using Doxygen. Go to the `doc/doxygen` folder and issue `doxygen`, you should find the html documentation in `_build/html/index.html` afterwards.

**Comment by bhourahine** [comment]
The documentation is now also visible on Read the Docs.
