### ISSUE TITLE
NUMROC wrapping

### ISSUE THREAD

**Issue by bhourahine** [dftbplus/scalapackfx#9]
Would be useful to be able to simply query local storage requirements for arrays like eigenvalues, pivot arrays etc.

**Comment by aradi** [comment]
At the moment we only have a `getlocalshape` routine in `scalapackfx.F90`.  Do you have something else in mind, which is not covered there?

**Comment by bhourahine** [comment]
Yes, several smaller arrays are also distributed, so do not necessarily need to be allocated at the global size on each node. See for example the dimensioning of ipiv in http://www.netlib.org/scalapack/explore-html/df/dfe/pdgetrf_8f.html
